package com.damyan.sf.basic;


/**
 * @author Damyan Damyanov <damyan.damyanov@scalefocus.com>
 */
public class Main {
    public static void main(String[] args) {
        Session session = new Session();

        /*
         * 1. DaggerGameComponent is generated by Dagger including the create() function.
         *
         * 2. It will create a GameComponent implementation, in which we can call inject() with our Session.
         *
         * 3. The inject() method will take care to inject all the defined dependencies for that object.
         */
        DaggerGameComponent.create().inject(session);

        // Use the injected data
        System.out.println(session.data.userData);
    }
}
